
package io.credable.cbs.transaction;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransactionDataPort", targetNamespace = "http://credable.io/cbs/transaction")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransactionDataPort {


    /**
     * 
     * @param transactionsRequest
     * @return
     *     returns io.credable.cbs.transaction.TransactionsResponse
     */
    @WebMethod(operationName = "Transactions")
    @WebResult(name = "TransactionsResponse", targetNamespace = "http://credable.io/cbs/transaction", partName = "TransactionsResponse")
    public TransactionsResponse transactions(
        @WebParam(name = "TransactionsRequest", targetNamespace = "http://credable.io/cbs/transaction", partName = "TransactionsRequest")
        TransactionsRequest transactionsRequest);

}
